
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('recipes').del()
    .then(function () {
      // Inserts seed entries
      return knex('recipes').insert([
        {id: 1, foodType: "chicken",
              recipeName: "Citrus Roasted Chicken",
                calories: 2643,
               recipeUrl: "https://food52.com/recipes/3403-citrus-roasted-chicken",
          numIngredients: 6,
       ingredientsString: "1 chicken, about 3.5 to 4 pounds \n 1 lemon \n 1 blood orange \n 1 tangerine or clementine \n Kosher salt \n 1/2 cup chicken broth"
        },
        {id: 2, foodType: "chicken",
               recipeName: "Roast Chicken",
                 calories: 2384,
                    yield: 4,
                recipeUrl: "http://www.epicurious.com/recipes/food/views/Roast-Chicken-394676",
           numIngredients: 3,
        ingredientsString: "1 tablespoon kosher salt \n 1 whole 4-pound chicken, giblets reserved for another use \n 1/4 cup (1/2 stick) unsalted butter, melted"
        },
        {id: 3, foodType: "chicken",
               recipeName: "Thomato Chicken",
                 calories: 2027,
                    yield: 3,
                recipeUrl: "http://www.bbcgoodfood.com/recipes/94602/thomato-chicken",
           numIngredients: 12,
        ingredientsString: "2 chicken breasts \n 2 tsp capers \n 1 large onion \n 6 cherry tomatoes \n 1.5 tsp oregano \n 3 tsps of tomato puree \n 1 red pepper \n 1 tin chopped tomatoes \n 5 sun-dried tomatoes \n 1 tsp basil \n Salt and pepper to taste \n Olive oil for frying chicken"
        },
        {id: 4, foodType: "chicken",
               recipeName: "Chicken Paprika",
                 calories: 3804,
                    yield: 6,
                recipeUrl: "http://www.bbc.co.uk/food/recipes/chickenpaprikawithle_80341",
           numIngredients: 14,
        ingredientsString: "1 large chicken, jointed (or use 2 large chicken legs and 2 breasts, halved) \n Salt \n 2 tbsp olive oil \n Knob butter \n 1 onion, chopped \n 2-3 cloves garlic, chopped \n 1 tbsp sweet paprika \n 1 tbsp hot paprika \n 1 tbsp flour \n 285ml/½pint chicken stock \n 3 tbsp chopped fresh flatleaf parsley \n 2 red peppers, de-seeded and cut into 1cm/0.5in strips \n 4 large ripe tomatoes, roughly chopped \n 250ml/8fl oz sour cream"
        },
        {id: 5, foodType: "chicken",
               recipeName: "Circassian Chicken",
                 calories: 2808,
                    yield: 4,
                recipeUrl: "http://simplyrecipes.com/recipes/circassian_chicken/",
           numIngredients: 13,
        ingredientsString:  "2 full chicken breasts (both halves) /n 4 tablespoons olive or walnut oil /n 4 teaspoons paprika /n 1 ½ cups chopped walnuts /n 3 chopped garlic cloves /n 2 tablespoons chopped green onions /n 1 teaspoon cayenne /n 2 tablespoons chopped parsley /n 2 slices of bread, crusts removed /n 1 quart chicken stock /n Salt /n Black pepper /n The juice of a lemon"
        },
        {id: 6, foodType: "chicken",
               recipeName: "Baked Enchilada Chicken",
                 calories: 3604,
                    yield: 6,
                recipeUrl: "http://www.kitchendaily.com/recipe/baked-enchilada-chicken",
           numIngredients: 2,
        ingredientsString: "3 ½ lb chicken parts /n 1 cup prepared enchilada sauce"
        },
        {id: 7, foodType: "chicken",
               recipeName: "Teriyaki Chicken",
                 calories: 2618,
                    yield: 4,
                recipeUrl: "https://www.realsimple.com/food-recipes/browse-all-recipes/teriyaki-chicken",
           numIngredients: 4,
        ingredientsString: "1  3 1/2- to 4-pound chicken, cut into pieces /n 1/2 cup bottled teriyaki sauce /n 1 teaspoon kosher salt /n 1/2 teaspoon black pepper"
        },
        {id: 8, foodType: "chicken",
               recipeName: "Cracklin’ Chicken",
                 calories: 2709,
                    yield: 4,
                recipeUrl: "http://nomnompaleo.com/post/74180911762/cracklin-chicken",
           numIngredients: 4,
        ingredientsString: "8 bone-in, skin-on chicken thighs (approximately 4 pounds) /n 1 tablespoon Diamond Crystal kosher salt /n 2 teaspoons ghee /n 2 teaspoons seasoning blend of choice (optional)"
        },
        {id: 9, foodType: "chicken",
               recipeName: "Chicken And Dumplings Recipe",
                 calories: 5172,
                    yield: 8,
                recipeUrl: "http://www.foodrepublic.com/2011/06/19/chicken-and-dumplings-recipe",
           numIngredients: 9,
        ingredientsString: "12 cups chicken broth /n 1 rotisserie chicken /n 3 cups self-rising flour, plus more for countertop /n 1/8 teaspoon dried sage /n 1/8 teaspoon dried thyme /n 1/4 teaspoon dried oregano /n 1/4 teaspoon freshly ground black pepper /n 6 tablespoons Crisco shortening /n 1 cup milk"
        },
        {id: 10, foodType: "chicken",
                recipeName: "Chicken & Peppers",
                  calories: 1197,
                     yield: 2,
                 recipeUrl: "http://thestonesoup.com/blog/2012/05/the-1-thing-you-should-never-do-when-combining-flavours/",
            numIngredients: 2,
         ingredientsString: "4-6 chicken drumsticks /n 2-3 large red capsicum (bell peppers), chopped"
       },
       {id: 11, foodType: "beef",
               recipeName: "Grilled And Roasted Beef",
                 calories: 3801,
                    yield: 6,
                recipeUrl: "http://ruhlman.com/2011/12/grill-roast-beef-recipe/",
           numIngredients: 4,
        ingredientsString: "One 6-pound/2.7-kilogram rack of beef /n Kosher salt /n” 2 tablespoons canola or olive oil /n 2 teaspoons coarsely cracked or chopped black pepper /n 2 teaspoons coarsely cracked coriander seeds"
       },
       {id: 12, foodType: "beef",
               recipeName: "Grilled Beef Tenderloin",
                 calories: 5389,
                    yield: 8,
                recipeUrl: "http://www.marthastewart.com/319496/grilled-beef-tenderloin",
           numIngredients: 4,
        ingredientsString: "1 beef tenderloin (4 pounds), preferably grass fed (estanciabeef.com), trimmed and tied /n Extra-virgin olive oil, for rubbing /n Coarse salt and freshly ground pepper /n 1/2 cup mint-chive butter"
        },
        {id: 13, foodType: "beef",
                recipeName: "Beef Stew",
                  calories: 2582,
                     yield: 4,
                 recipeUrl: "http://www.epicurious.com/recipes/food/views/Beef-Stew-358272",
            numIngredients: 12,
         ingredientsString: "1/2 cup flour /n 1 teaspoon salt /n 1/4 teaspoon pepper /n 2 pounds stew beef, cubed /n 3 teaspoons olive oil or butter /n 1 bay leaf /n 1 clove garlic, smashed /n 1 beef stock cube /n 1 pound small onions /n 6 carrots, sliced /n 3 medium-size potatoes, quartered /n 1 package frozen peas"
        },
        {id: 14, foodType: "beef",
                recipeName: "Beef Wellington Recipe",
                  calories: 3803,
                     yield: 6,
                 recipeUrl: "http://www.foodrepublic.com/2011/12/21/beef-wellington-recipe",
            numIngredients: 10,
         ingredientsString: "2 1/2 pounds beef tenderloin /n 2 tablespoons olive oil /n 3 tablespoons butter /n 1 1/2 cups button mushrooms, quartered /n 1 cup porcini mushrooms, quartered /n 5 shallots peeled and finely chopped /n 1 small bunch parsley /n 2 slices sandwich bread, torn into pieces /n puff pastry /n 1 egg yolk /n"
        },
        {id: 15, foodType: "beef",
                recipeName: "Quick Beef Tacos",
                  calories: 2880,
                     yield: 4,
                 recipeUrl: "https://www.realsimple.com/food-recipes/browse-all-recipes/beef-tacos-recipe",
            numIngredients: 8,
         ingredientsString: "1 1/2 pounds ground beef /n 1 teaspoon ground cumin /n 1 1/2 cups jarred salsa /n kosher salt /n 8  taco shells /n 1  avocado, diced /n 1/2 cup sour cream /n 1 cup fresh cilantro"
        },
        {id: 16, foodType: "beef",
                recipeName: "Quick Beef Stroganoff",
                  calories: 2379,
                     yield: 4,
                 recipeUrl: "http://www.myrecipes.com/recipe/quick-beef-stroganoff-3",
            numIngredients: 9,
         ingredientsString: "2 tablespoons  extra-virgin olive oil /n 1   onion, thinly sliced /n 8 ounces  cremini mushrooms, thinly sliced /n 1 teaspoon  chopped thyme /n Kosher salt and freshly ground pepper /n 1 cup  reserved gravy from Coriander-Dusted Roast Beef or other beef gravy /n 1/4 cup  sour cream /n Half of the Coriander-Dusted Roast Beef or 12 ounces roast beef, sliced 1/4 inch thick and cut into strips /n Buttered noodles, for serving"
        },
        {id: 17, foodType: "beef",
               recipeName: "Seared Beef and Noodle Soup",
                 calories: 2502,
                    yield: 4,
                recipeUrl: "http://www.pbs.org/food/recipes/seared-beef-and-noodle-soup/",
           numIngredients: 13,
        ingredientsString: "1/2 lb. rice noodles /n 1 1/4 lbs. beef sirloin (about 1 inch thick) /n Salt and pepper /n 2 tablespoons olive oil /n 10 ounces white mushrooms sliced /n 2 cloves garlic minced /n 6 cups beef stock or reduced-sodium canned broth /n 3 tablespoons soy sauce /n 2 teaspoons rice-wine vinegar /n 2 carrots cut into thin strips /n 1/2 napa cabbage shredded /n 2 scallions including green parts, thinly sliced /n 1 cup bean sprouts"
        },
        {id: 18, foodType: "beef",
               recipeName: "Beef and Noodles",
                 calories: 4236,
                    yield: 6,
                recipeUrl: "https://www.foodnetwork.com/recipes/beef-and-noodles-recipe-2012887",
           numIngredients: 14,
        ingredientsString: "8 ounces beef bones /n 1/3 pound carrots, coarsely chopped /n 1/3 pound celery, coarsely chopped /n 1/3 pound yellow onion, coarsely chopped /n 1 ounce instant au jus powder or 5 beef bouillon cubes, crushed /n 1/2 teaspoon granulated garlic /n 2 pounds beef roast, inside round or top round /n 8 cups beef stock /n 3 1/2 cups all-purpose flour, plus for dusting /n 1 teaspoon salt /n 2 eggs /n 4 egg yolks /n 2 teaspoons oil /n Salt and freshly ground black pepper"
        },
        {id: 19, foodType: "beef",
               recipeName: "Plum-Spiced Beef Brisket",
                 calories: 5326,
                    yield: 8,
                recipeUrl: "http://www.goodhousekeeping.com/food-recipes/a5861/plum-spiced-beef-brisket-3144/",
           numIngredients: 14,
        ingredientsString: "3 tbsp. toasted sesame oil /n 3½ lb. beef brisket /n 2 tsp. salt /n 1 tsp. fresh ground pepper /n 4 can low-sodium beef broth /n 2 c. dried plums /n 1/2 c. Worcestershire sauce /n 1/2 c. low-sodium soy sauce /n 6 clove garlic /n 2 tbsp. finely chopped ginger /n 2 tbsp. dark brown sugar /n 2 tbsp. apple-cider vinegar /n 1 tsp. five-spice powder /n 1/2 tsp. crushed red pepper"
       },
       {id: 20, foodType: "beef",
              recipeName: "Goan Beef and Chili Stir Fry",
                calories: 2555,
                   yield: 4,
               recipeUrl: "http://honestcooking.com/goan-beef-and-chili-stir-fry/",
          numIngredients: 9,
       ingredientsString: "2 lbs cubed beef (stew beef pieces preferably) /n 4 medium sized potatoes /n 2 large red onions /n 2 cloves of garlic /n 1 teaspoon grated ginger root /n 1 teaspoon garam masala /n 4 medium sized green chilies /n Salt and pepper to taste /n 4 tablespoons vegetable oil"
       },
       {id: 21, foodType: "pork",
              recipeName: "Easy Pork Shoulder",
                calories: 5644,
                   yield: 9,
               recipeUrl: "http://www.marthastewart.com/343825/easy-pork-shoulder",
          numIngredients: 4,
       ingredientsString: "1 boneless pork shoulder (7 pounds) /n coarse salt /n“ ground pepper /n 1/2 cup water /n"
       },
       {id: 22, foodType: "pork",
              recipeName: "Flæskesteg - Danish Roast Pork",
                calories: 2772,
                   yield: 4,
               recipeUrl: "http://honestcooking.com/flaeskesteg-danish-roast-pork-recipe/",
          numIngredients: 4,
       ingredientsString: "1 5-lb. slab of pork tenderloin, with rind and fat intact /n Dried bay leaves /n Whole cloves /n Sea salt and pepper"
       },
       {id: 23, foodType: "pork",
              recipeName: "Double-Pork Carnitas",
                calories: 5653,
                   yield: 8,
               recipeUrl: "https://www.epicurious.com/recipes/food/views/pork-carnitas-tacos",
          numIngredients: 12,
       ingredientsString: "3 pounds boneless pork shoulder (Boston butt), cut into 1 1/2-inch pieces /n 1 pound pork belly, cut into 1-inch pieces /n 1 cup homemade chicken stock or low-sodium chicken broth /n 1 tablespoon (heaping) kosher salt /n 1 teaspoon freshly ground black pepper /n Warm corn tortillas, chopped white onion, lime wedges, sliced avocado, dried oregano, chopped cilantro, and shredded cabbage (for serving)"
       },
       {id: 24, foodType: "pork",
              recipeName: "Pork With Creamy Pear Sauce",
                calories: 2649,
                   yield: 4,
               recipeUrl: "http://www.bbcgoodfood.com/recipes/13456/pork-with-creamy-pear-sauce",
          numIngredients: 7,
       ingredientsString: "350 ml cream /n 3 spring onions, finely sliced /n 1 pear, diced /n Salt and pepper /n 1 tbsp butter or margarine /n 1 tbsp extra-virgin olive oil /n 900 g pork tenderloin"
       },
       {id: 25, foodType: "pork",
              recipeName: "Pork Vindaloo",
                calories: 2519,
                   yield: 4,
               recipeUrl: "https://food52.com/recipes/1739-pork-vindaloo",
          numIngredients: 15,
       ingredientsString: "1 1/2 pound pork /n 1 teaspoon cumin /n 1/4 teaspoon turmeric /n 2 teaspoons mustard /n 1 pod garlic /n 1 inch ginger /n 4 dry red chilly (remove seed) /n 4 clove /n 1 inch stick cinnamon /n 1 teaspoon pepper /n 1 tablespoon raisin /n 1 teaspoon sugar /n 1/2 cup cider vinegar /n 3/4 pounds tomato /n 1/2 cup oil"
       },
       {id: 26, foodType: "pork",
              recipeName: "Juicy Buttermilk Pork Chops",
                calories: 2383,
                   yield: 4,
               recipeUrl: "http://www.kitchendaily.com/recipe/juicy-buttermilk-pork-chops",
          numIngredients: 4,
       ingredientsString: "4 1-inch thick bone-in pork rib chops, about 12 ounce each /n 1 qt buttermilk /n salt and freshly ground black pepper /n 2 Tbsp extra virgin olive oil"
       },
       {id: 27, foodType: "pork",
              recipeName: "Sweet And Tangy Pork Chops",
                calories: 2445,
                   yield: 4,
               recipeUrl: "http://www.cookstr.com/recipes/sweet-and-tangy-pork-chops",            numIngredients: 4,
       ingredientsString: "1/2 cup Neely's Barbecue Seasoning /n 2 cups Neely’s Barbecue Sauce /n Four 1-inch-thick bone-in center-cut pork chops /n Kosher salt"
       },
       {id: 28, foodType: "pork",
              recipeName: "Indoor Pulled Pork",
                calories: 3763,
                   yield: 6,
               recipeUrl: "http://www.thebittenword.com/thebittenword/2010/01/indoor-pulled-pork-and-other-superbowl-food-ideas.html",
          numIngredients: 8,
       ingredientsString: "1 cup plus 2 tsps table salt /n 1/2 cup plus 2 tbsps sugar /n 3 tbsps plus 2 tsps liquid smoke /n 1 boneless pork butt (about 5 lbs), cut in half horizontally /n 1/4 cup yellow mustard /n 2 tbsps ground black pepper /n 2 tbsps smoked paprika /n 1 tsp cayenne pepper"
       },
       {id: 29, foodType: "pork",
              recipeName: "Braised Hawaiian Pork Shoulder",
                calories: 2566,
                   yield: 4,
               recipeUrl: "http://www.cookingchanneltv.com/recipes/brian-boitano/braised-hawaiian-pork-shoulder.html",
          numIngredients: 13,
       ingredientsString: "1 tablespoon brown sugar /n 2 teaspoons red hawaiian sea salt or kosher salt /n 2 teaspoons paprika /n 1/2 teaspoon ground cumin /n 1/2 teaspoon ground coriander /n 1/2 teaspoon freshly cracked black pepper /n 1 1/2 pounds pork shoulder or boston pork butt /n 1/4 cup canola oil, divided /n 1 onion, chopped /n 1 (3-inch) piece ginger, sliced /n 4 cloves garlic, smashed /n 1 cup pineapple juice /n 2 cups chicken stock or broth"
       },
       {id: 30, foodType: "pork",
              recipeName: "Fennel and Chili-Rubbed Pork Roast",
                calories: 4861,
                   yield: 8,
               recipeUrl: "http://www.thedailymeal.com/recipes/fennel-and-chili-rubbed-pork-roast-recipe",
          numIngredients: 5,
       ingredientsString: "5 Pounds pork ribeye roast, or bone-in pork loin roast /n Sea salt, to taste /n 1/3  Cup fennel seed, toasted /n 1 1/2 Tablespoon red chili flake, toasted /n 2 Tablespoons olive oil"
       }
      ]);
    });
};
